export enum ProductsActionType {
  GET_PRODUCTS = 'PRODUCTS_GET_PRODUCTS',
  SAVE_GOT_PRODUCTS = 'PRODUCTS_SAVE_GOT_PRODUCTS',
  CREATE_PRODUCT = 'PRODUCTS_CREATE_PRODUCT',
  SAVE_CREATED_PRODUCT = 'PRODUCTS_SAVE_CREATED_PRODUCT',
  EXECUTE_PRODUCT = 'PRODUCTS_EXECUTE_PRODUCT',
  SAVE_EXECUTED_PRODUCT_RESULT = 'PRODUCTS_SAVE_EXECUTED_PRODUCT_RESULT',
}
